# Generated by Django 3.2.3 on 2021-05-25 16:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('totalArea', models.IntegerField(default=None)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326)),
            ],
            options={
                'db_table': 'plot',
                'managed': True,
            },
        ),
    ]
